apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
data:
  application.properties: |-
    minion.art="<p style=\" size:13px; font-family:'lucida grande', tahoma, verdana, arial, sans-serif; line-height:18px; color:black\">\
                               ──────────▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄<br/>\
                               ────────█═════════════════█<br/>\
                               ──────█═════════════════════█<br/>\
                               ─────█════════▄▄▄▄▄▄▄════════█<br/>\
                               ────█════════█████████════════█<br/>\
                               ────█═══════██▀─────▀██═══════█<br/>\
                               ───███████████──█▀█──███████████<br/>\
                               ───███████████──▀▀▀──███████████<br/>\
                               ────█═══════▀█▄─────▄█▀═══════█<br/>\
                               ────█═════════▀█████▀═════════█<br/>\
                               ────█═════════════════════════█<br/>\
                               ────█══════▀▄▄▄▄▄▄▄▄▄▀════════█<br/>\
                               ───▐▓▓▌═════════════════════▐▓▓▌<br/>\
                               ───▐▐▓▓▌▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▐▓▓▌▌<br/>\
                               ───█══▐▓▄▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▄▓▌══█<br/>\
                               ──█══▌═▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌═▐══█<br/>\
                               ──█══█═▐▓▓▓▓▓▓▄▄▄▄▄▄▄▓▓▓▓▓▓▌═█══█<br/>\
                               ──█══█═▐▓▓▓▓▓▓▐██▀██▌▓▓▓▓▓▓▌═█══█<br/>\
                               ──█══█═▐▓▓▓▓▓▓▓▀▀▀▀▀▓▓▓▓▓▓▓▌═█══█<br/>\
                               ──█══█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█══█<br/>\
                               ─▄█══█▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌█══█▄<br/>\
                               ─█████▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌─█████<br/>\
                               ─██████▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌─██████<br/>\
                               ──▀█▀█──▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌───█▀█▀<br/>\
                               ─────────▐▓▓▓▓▓▓▌▐▓▓▓▓▓▓▌<br/>\
                               ──────────▐▓▓▓▓▌──▐▓▓▓▓▌<br/>\
                               ─────────▄████▀────▀████▄<br/>\
                               ─────────▀▀▀▀────────▀▀▀▀</p>"\
    minion.type=one-eyed-minion